services:
  postgres:
    image: postgres:16
    container_name: meetnote-postgres-compose
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-meetnote_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-meetnote_chat_compose}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    networks:
      - meetnote-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-meetnote_user} -d ${POSTGRES_DB:-meetnote_chat_compose}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meetnote-chat-compose
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - '${PORT:-3001}:${PORT:-3001}'
    networks:
      - meetnote-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  meetnote-network:
    driver: bridge
