apiVersion: v1
kind: Secret
metadata:
  name: chat-secret
type: Opaque
data:
  jwt-secret: MzcwYjg2NmEtODEwMC00ZDdhLTk0ODctNzY3ZDI4NWQ4ZGUw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
data:
  NODE_ENV: 'production'
  PORT: '3001'
  LOG_LEVEL: 'info'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: badal1/meetnote-chat-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3001
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: NODE_ENV

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: PORT

            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: chat-config
                  key: LOG_LEVEL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: jwt-secret
            - name: DATABASE_URL
              value: 'postgresql://meetnote_user:$(POSTGRES_PASSWORD)@postgres-svc:5432/meetnote_chat_k8s?sslMode=disable'
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          startupProbe:
            httpGet:
              path: /api/v1/chat/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/v1/chat/health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/chat/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-svc
  labels:
    app: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-service-ingress
spec:
  rules:
    - host: chat.meetnote.local
      http:
        paths:
          - path: /api/v1/chat
            pathType: Prefix
            backend:
              service:
                name: chat-service-svc
                port:
                  name: http
